# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: always

#  redis:
#    image: redis
#    ports:
#      - "6379:6379"
